//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelwhims.Models.TWdatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int id { get; set; }
        public string n_titile { get; set; }
        public string n_notice { get; set; }
        public byte[] n_datetime { get; set; }
    }
}
